language: c

include: &toolchain_linux_amd64
  os: linux
  dist: trusty
  addons:
    apt:
      update: true

include: &toolchain_linux_386
  os: linux
  dist: trusty
  addons:
    apt:
      packages:
        - gcc-multilib
        - g++-multilib

include: &toolchain_osx_amd64
  os: osx
  osx_image: xcode8

matrix:
  include:
    - env: linking=shared arch=amd64
      <<: *toolchain_linux_amd64
    - env: linking=static arch=amd64
      <<: *toolchain_linux_amd64
    - env: linking=shared arch=386
      <<: *toolchain_linux_386
    - env: linking=static arch=386
      <<: *toolchain_linux_386
    - env: linking=shared arch=amd64
      <<: *toolchain_osx_amd64
    - env: linking=static arch=amd64
      <<: *toolchain_osx_amd64

install:
  - if [[ "${arch}" == "386" ]]; then
      export CFLAGS=-m32;
      export CXXFLAGS=-m32;
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig;
    fi
  - if [[ "${linking}" == "static" ]]; then
      export CMAKE_FLAGS=-DBUILD_SHARED_LIBS=OFF;
    fi

script:
  - cmake --version
  - mkdir build
  - pushd build
  - cmake -G "Unix Makefiles" ${CMAKE_FLAGS} ..
  - make
  - popd

after_success:
  - ls -lR build/bin
  - file build/bin/cat
  - file build/bin/echo
  - export platform="$TRAVIS_OS_NAME"
  - if [[ "x${TRAVIS_TAG}" != "x" ]]; then export version=${TRAVIS_TAG}; else export version=${TRAVIS_BRANCH}; fi
  - export artifact=${version}-${platform}-${arch}-${linking}
  - echo ${artifact}
  - pushd build/bin
  - tar -czvf base-utils-${artifact}.tar.gz *
  - popd

deploy:
  provider: releases
  api_key:
    secure:[GITHUB_OAUTH_TOKEN]
  file: build/bin/*.tar.gz
  file_glob: true
  skip_cleanup: true